### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by frogg** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#12]
It should be indicated that game is loading its content (instead of black screen)

**Comment by 5chdn** [comment]
good point. we should also consider embedding it into something different than a white background.

**Comment by frogg** [comment]
https://www.youtube.com/watch?v=oNobWzmR7nQ

**Comment by benmaier** [comment]
closed in eef173bb10788ad65bcfb7660d2c6ffdd016b6b3
