### ISSUE TITLE
Swipe Gesture reagiert manchmal nicht richtig

### ISSUE THREAD

**Issue by frogg** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#13]
Wenn man spielt kann es vorkommen, dass die Swipe Geste in einem Moment nicht richtig funktioniert. Kann es sein, dass in gewissen Render-Abschnitten die Geste nicht erkannt wird? Kann man das irgendwie asynchron regeln?

**Comment by benmaier** [comment]
hm, die swipe-erkennung laeuft eigentlich im Hintergrund durch ein extra Objekt, welches dann in der update-funktion ausgelesen wird. bewegungen werden aber nur alle 200ms zugelassen, wenn in denen was passiert wird es ignoriert. wir koennten entweder die zeit runterschrauben oder events stacken und nacheinander ausfuehren. schau ich mir mal an

**Comment by frogg** [comment]
ah ok, das würde es erklären. welches Parameter ist das denn? dann kann ich das mal ausprobieren

**Comment by benmaier** [comment]
`key_change_rate`, zeile 130

**Comment by benmaier** [comment]
kann auch sein, dass die bibliothek `swipe.js` zu kurze swipes nicht erkennt

**Comment by frogg** [comment]
yep, ich glaube daran liegt es. Kann man die swipe-länge selber definieren?

**Comment by benmaier** [comment]
ich probier mal rum

**Comment by benmaier** [comment]
hotfixed. probier mal. ich hab jetzt noch hinzugefuegt, dass auch diagonale swipes erkannt werden.

allerdings ist noch problematisch (ist es?, ich kenn mich zuwenig aus), dass kein swipe erkannt wird, wenn man nicht den finger absetzt. D.h. wenn du da nach rechts und gleich wieder nach links willst, wird das "nach links" nicht erkannt. Wie ist das normalerweise bei android und iOS?
