### ISSUE TITLE
Europa-Mouds: Kilometeranzeige muss schneller ansteigen

### ISSUE THREAD

**Issue by frogg** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#15]
Wenn der Zug schneller fährt müssen auch mehr km hinzugefügt werden

**Comment by 5chdn** [comment]
das hängt mit #5 zusammen, da die geschwindigkeit ja dynamisch ist. @benmaier hast du da spontan eine idee? momentan mache ich nur distance++ in update()

**Comment by benmaier** [comment]
jo, hab ich! mach ich
