### ISSUE TITLE
Crashing into wall: more damage

### ISSUE THREAD

**Issue by frogg** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#16]
Im moment kann man das Spiel einfach liegen lassen und es wird mehr Punkte einsammeln als durch Wall-Crashs wieder verloren gehen. D.h. man kann das Handy einfach liegen lassen und in endlicher Zeit hohe Punktestände erreichen, ohne dafür etwas getan zu haben.
Wände sollten deshalb größere Punktabzüge bewirken, oder?

**Comment by 5chdn** [comment]
Ja, das ist mir auch aufgefallen. -100 :)

**Comment by benmaier** [comment]
ref #22
