### ISSUE TITLE
Audio on iOS not working anymore

### ISSUE THREAD

**Issue by frogg** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#18]
Wurde an der Sound Wiedergabe etwas geändert? Unter iOS höre ich nun leider keine Sound Effekte mehr. Desktop funktioniert allerdings noch.

**Comment by benmaier** [comment]
wann hat es denn das letzte mal funktioniert? ich hab gestern vormittag die WAVs  zu MP3s/OGGs gewechselt. moment, ich probier mal was

**Comment by benmaier** [comment]
ich hab was gepushed, probier mal aus

**Comment by frogg** [comment]
hmm bin mir auch nicht sicher woran es liegt. Normalen iOS Browser funktioniert es jedenfalls auch nicht mehr. Habe deine Version gerade ausprobiert, leider funktioniert es nicht.

**Comment by benmaier** [comment]
shit. kann das irgendwie an dem switch liegen?

**Comment by frogg** [comment]
Ich habe den Fehler gefunden: Und zwar startet das Audio auf iOS nur, wenn man per Touch mit dem Game interagiert (keine Ahnung warum). Ich habe jedoch die Userinteraction deaktiviert, um unsere eigenen Gesturerecognizer zu integrieren. 
Habe die Userinteraction jetzt wieder aktiviert und über einen Umweg die Gesturerecognizer trotzdem nativ drin – funktioniert jetzt also!

**Comment by benmaier** [comment]
sauber :)
