### ISSUE TITLE
Add new asset for Gottkanzler Mode

### ISSUE THREAD

**Issue by frogg** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#2]
When collecting EU stars the train asset should be changed to a bright shining Gottkanzler-Zug asset instead of the collision one.

**Comment by 5chdn** [comment]
Yes, indeed. It was one of the last-minute features @benmaier implemented.

**Comment by frogg** [comment]
Blauer Rauch ist ja schon drin oder?

**Comment by benmaier** [comment]
ja. irgendwas funkelndes waere aber auch noch cool. oder wenn der Zug blau ist

**Comment by frogg** [comment]
In der Tat! Glänzen/Glühen/Götterfunken

**Comment by 5chdn** [comment]
siehe #38 - muss nur jemand mal einbauen.

**Comment by 5chdn** [comment]
ist drin :)
