### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by benmaier** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#30]
Initial or future release?

**Comment by frogg** [comment]
Muss initial sein. Ist denke ich auch kein großer Aufwand das in ein Android WebView reinzuladen.

Kennt sich jemand von euch mit Android aus?

**Comment by benmaier** [comment]
Ich nicht. habe gerade das hier gefunden http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/

**Comment by nikriek** [comment]
Ich hab mal android gemacht..

**Comment by benmaier** [comment]
Irgendwelche Tipps fuer noobs? :) du bist ja erstmal im Urlaub, nich?

**Comment by nikriek** [comment]
no(o)p, sorry. Lad dir vllt mal android studio und teste aus. Im Grunde reicht ja ein simples wrapping. Sollte auch ohne große Kenntnisse machbar sein.

**Comment by benmaier** [comment]
kk

**Comment by nikriek** [comment]
https://developer.android.com/reference/android/webkit/WebView.html

**Comment by nikriek** [comment]
https://developer.chrome.com/multidevice/webview/gettingstarted

**Comment by nikriek** [comment]
Die Anleitung sollte eigentlich alles abdecken

**Comment by benmaier** [comment]
alles klar, danke!

**Comment by benmaier** [comment]
to resolve the `let`-`var`-bug: 
http://stackoverflow.com/a/2356926/4177832

**Comment by benmaier** [comment]
Done.
