### ISSUE TITLE
Wenn man blinkt kann man keine Coins/Sterne einsammeln

### ISSUE THREAD

**Issue by frogg** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#31]
…dass man nicht direkt nochmal in eine Wand reinkracht ist gut, aber ich denke Sterne und Coins sollte man trotzdem aufsammeln können

**Comment by benmaier** [comment]
findest du? ich find das eigentlich ne gerechte strafe :)

**Comment by 5chdn** [comment]
ich sehe das auch als 'feature'.
