### ISSUE TITLE
Update assets and animations

### ISSUE THREAD

**Issue by 5chdn** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#38]
via telegram

 - [x] ~~https://cloud.githubusercontent.com/assets/15729797/23811933/61d6cad6-05d8-11e7-93dc-29f55cac8165.png~~ replaced
- [ ] ![star_animation](https://cloud.githubusercontent.com/assets/15729797/23811934/61dbf952-05d8-11e7-846c-b91ee50e0f91.png)

**Comment by 5chdn** [comment]
![trains_star](https://cloud.githubusercontent.com/assets/15729797/23813468/56de0656-05df-11e7-8ab5-740f2a94322f.png)
![trains_normal](https://cloud.githubusercontent.com/assets/15729797/23813471/56ee4ab6-05df-11e7-8084-a9f3f9354fba.png)
![trains_extra](https://cloud.githubusercontent.com/assets/15729797/23813470/56e254c2-05df-11e7-8cdd-51ea793fe745.png)
![trains_collision](https://cloud.githubusercontent.com/assets/15729797/23813469/56e07652-05df-11e7-8b31-5d876b4925a8.png)

**Comment by 5chdn** [comment]
![goat](https://cloud.githubusercontent.com/assets/15729797/23814059/18fccfa4-05e2-11e7-8377-357ad137c16e.png)

**Comment by 5chdn** [comment]
![gate](https://cloud.githubusercontent.com/assets/15729797/23814953/f3d43c86-05e5-11e7-9f52-6c921f3f79cf.png)
![putin_bear](https://cloud.githubusercontent.com/assets/15729797/23814952/f3d3f1cc-05e5-11e7-9494-957e7b6a3122.png)

**Comment by 5chdn** [comment]
- [ ] ![tree03](https://cloud.githubusercontent.com/assets/15729797/23815324/fffa9440-05e7-11e7-9f71-d3254398681b.png)
- [ ] ![trains_collision 2](https://cloud.githubusercontent.com/assets/15729797/23815326/0019f204-05e8-11e7-885c-9b283288999a.png)

**Comment by 5chdn** [comment]
- [ ] ![schulzzug_logo](https://cloud.githubusercontent.com/assets/15729797/23817481/c4f2d126-05f3-11e7-9983-c4954bbddd96.png)

**Comment by benmaier** [comment]
@5chdn @CedTheBat This is done, right?

**Comment by 5chdn** [comment]
ich habe die assets erstmal nur hier rein kopiert. noch nicht im repository, unless @CedTheBat did it.
