### ISSUE TITLE
Redundant time variable?

### ISSUE THREAD

**Issue by frogg** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#41]
```
    //time handling
    let time_last = time_now;
    time_now = game.time.now;
    let time = time_now;
    let time_delta = time - time_last;

```

`let time = time_now;` is this necessary? We could use time_now instead.

**Comment by 5chdn** [comment]
grown historically, `time` is the local scope of global `time_now` in `update()`

should be safe to replace `time` by `time_now` ...
