### ISSUE TITLE
Musik

### ISSUE THREAD

**Issue by benmaier** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#42]
Ich mach grad ein bisschen mucke und hab voll bock "die Internationale" als 8bit-Version zu machen, das koennte man als Hintergrundmusik benutzen. Hat da wer was gegen?

**Comment by CedTheBat** [comment]
find ich gut!

**Comment by benmaier** [comment]
ich hab mal das erste sample in 652e9403a3c0add17371c80acda4766d150e7659 hinzugefuegt, wenn's missfaellt nehmen wir's wieder raus.
