### ISSUE TITLE
framework for level changes

### ISSUE THREAD

**Issue by benmaier** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#44]
consistent framework, s.t. one can easily increase a level with all assets included.

**Comment by benmaier** [comment]
first published in 0851080fbd8d70707e2613c23c4af4edbc14e9a7

**Comment by benmaier** [comment]
@5chdn @frogg I suggest,we keep developing in this "state" framework, delete `schulzzug.js` and move `states.html` to `index.html`. Cool with you?

**Comment by 5chdn** [comment]
Go ahead. Will redesign the directory structure now, to prepare the firebase support #32
