### ISSUE TITLE
Losing focus stops animation but resumes distance counter

### ISSUE THREAD

**Issue by 5chdn** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#50]
Losing focus stops animation but resumes distance counter. Not sure why.

**Comment by benmaier** [comment]
cause it counts as

`distance += v*dt` and dt grows even if focus is lost

**Comment by 5chdn** [comment]
This also affects animations

**Comment by benmaier** [comment]
yup, I'm aware of this. I think there's a workaround by fetching the pause signal and rescaling time.

**Comment by benmaier** [comment]
`game.stage.disableVisibilityChange = true;` would forbid to lose focus :D
