### ISSUE TITLE
Grass does not move

### ISSUE THREAD

**Issue by 5chdn** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#52]
Grass does not move, only annoying in levels that have patterns (like USA)

**Comment by CedTheBat** [comment]
remove patterns, now flat color.

**Comment by benmaier** [comment]
is this done? if so, can you open a pull request? https://github.com/Bestes-SPD-Hackathon-Team/Schulzzug-JS/compare , then click on `graphics` in the list
