### ISSUE TITLE
Levels: put the right populists on the rails

### ISSUE THREAD

**Issue by benmaier** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#57]
according to the country. also requires a consistent probability norming.

**Comment by 5chdn** [comment]
+ Asset label. We dont have walls for all of them yet. @CedTheBat

**Comment by benmaier** [comment]
the framework exists now as per 805b529e7b77322b333de5e0354f74586f88d2d7

so we only need the assets now. I'm currently just using the upstanding sprites.
