### ISSUE TITLE
Can't play offline anymore

### ISSUE THREAD

**Issue by benmaier** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#62]
Causes firebase bug.

**Comment by frogg** [comment]
FYI: Unter iOS funktioniert offline ohne Probleme

**Comment by benmaier** [comment]
hm, stimmt. geht bei mir jetzt auch wieder. In der console gibt's nur den err `net::ERR_INTERNET_DISCONNECTED`

**Comment by frogg** [comment]
der kommt vermutlich wirklich von Firebird, aber kann man in dem Fall ja ignorieren
