### ISSUE TITLE
Add custom domain

### ISSUE THREAD

**Issue by nikriek** [Bestes-SPD-Hackathon-Team/Schulzzug-JS#7]

**Comment by nikriek** [comment]
For Github Pages we can just use a CNAME alias

**Comment by frogg** [comment]
<img width="697" alt="bildschirmfoto 2017-03-06 um 10 51 58" src="https://cloud.githubusercontent.com/assets/5204169/23604921/f2b293fe-025a-11e7-948f-d592b4035370.png">

**Comment by frogg** [comment]
schulzzug.eu scheint noch frei zu sein

**Comment by nikriek** [comment]
oder nen schönes domain hack

**Comment by 5chdn** [comment]
nen schöner domain mett

**Comment by frogg** [comment]
oder freundlich nachfragen, ob er sein CNAME ändert.
Die aktuelle Seite hat ja noch nicht viel Mehrwert, lässt aber erahnen, dass er für unsere Aktion offen sein könnte.

**Comment by frogg** [comment]
schulzzug.io ist auch noch frei 😃

**Comment by nikriek** [comment]
oder schulz🚂..ws

**Comment by benmaier** [comment]
ich persoenlich besitze noch die Domain hoheenergie.de und kenne denjenigen, der keinebremsen.de besitzt.

**Comment by benmaier** [comment]
was dagegen spricht, ist dass da meine Adresse im whois steht

**Comment by 5chdn** [comment]
> was dagegen spricht, ist dass da meine Adresse im whois steht

not good :)

**Comment by frogg** [comment]
schulzz.ug ist auch noch frei

**Comment by nikriek** [comment]
Nehmen wa, beste.

**Comment by 5chdn** [comment]
https://github.com/Bestes-SPD-Hackathon-Team/Schulzzug-JS/commit/a20eb6320d2beb4126cb0a3e306d1fb19495b60e
